name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
     - master

jobs:
  deploy:
      name: Deploy to server 
      runs-on: ubuntu-latest
  
      steps:
        - uses: actions/checkout@v3
        - name: Run playbook
          uses: dawidd6/action-ansible-playbook@v2
          with:
            playbook: playbook.yml
            directory: ansible
            options: |
              --inventory inventory.yml
              --extra-vars  "ansiblePassword=${{secrets.ANSIBLE_PASSWORD}} AnsibleUsername=${{secrets.ANSIBLE_USER}} AnsibleHost=${{secrets.ANSIBLE_HOST}}"

